### ISSUE TITLE
Include brief text description of project on homepage.

### ISSUE THREAD

**Issue by jsumnersmith** [birdsumner/dcrc#2]

**Comment by jsumnersmith** [comment]
I'm looking for a 2-3 sentence description of the project for the home page. Let me know what document you had in mind. The only thing close I could find was this:
https://drive.google.com/open?id=0BxY_QHj-4mxhdFN0a0FnV1k5Qlc2YzMyN2dYVjhOMThFYjV3&authuser=3

But it seems to not be a good 30,000 foot view of what's going on.

**Comment by brycehewlett** [comment]
How about something like this?

The Friends of Delaware State Hospital Cemetery Committee has undertaken a project to bring dignity to the people buried in a cemetery located on the Herman M. Holloway Sr. Campus in New Castle, DE – home to the Delaware State Hospital (now called Delaware Psychiatric Center) and the main offices of Delaware’s Department of Health and Social Services (DHSS). Resting in the cemetery are the people who lived out their days at the Delaware State Hospital. Presently, these people can only be identified by a single number on an otherwise plain headstone which corresponds to a ledger which was forgotten in an old book until recently rediscovered by a member of this committee. For more information click here.

**Comment by jsumnersmith** [comment]
I've added this description into the home page for now. It's hard-coded, which means it will be hard to change. In all likelihood, you will want to change that image and what it refers to as well, so we'll change that out when the home page needs to change.

http://delawarerecovery.org/
